main: com.github.dlsf.dasshop.DasShop
name: DasShop
version: '@version@'
api-version: '1.16'
author: das_
depend: [Vault]

commands:
  shop:
    description: Open the admin shop
  editshop:
    description: Edit the admin shop